### ISSUE TITLE
ENH: <sync version support>

### ISSUE THREAD

**Issue by wangxin688** [gufolabs/gufo_snmp#5]
### Proposed new feature or change:

appreciate hardworking on this project. Is there any possible to support sync version rather that async only?

**Comment by dvolodin7** [comment]
Rust part does not use async indeed. But timeout handling in syncronous code may be rather tricky

**Comment by wangxin688** [comment]
> Rust part does not use async indeed. But timeout handling in syncronous code may be rather tricky
I totally agree with you. Asyncio is better to handle io bound task. It's just a good option to use sync integrate with threading(sure i can run asyncio code in a separate thread). Cause a lot of history project was written with sync way.
Currently there is no good option for snmplibs to choose. pysnmp is good but with poor performance and API sucks.
easysnmp is fast for synchronize But pure C code is not maintainced anymore and lack of upgrading. As well as aiosnmp.
I saw you guys has developed noc system more than 7 years in netdevops field.
some things similar like netmiko nornir  in this field is sync way.

**Comment by wangxin688** [comment]
If that's is acceptable. Maybe I can make some contributions on that

**Comment by dvolodin7** [comment]
Sure, you are welcome.

To be correct, we're developing NOC for over than 16 years.

**Comment by dvolodin7** [comment]
Timeout handling may be implemented either by:

* Setting SO_RCVTIMEO socket option
* Prepending recv by select/epoll with timeout set

**Comment by wangxin688** [comment]
> Sure, you are welcome.
> 
> To be correct, we're developing NOC for over than 16 years.

amazing! I’m the new birds on netdevops ,although I have worked as network engineer more than 7 years. Your noc system is absolutely fantastic

**Comment by dvolodin7** [comment]
I've successfully implemented synchronous GET operations with minimal adjustments to the Rust core. However, we're currently facing challenges with getnext/getbulk, and I'm actively investigating and addressing these issues.

**Comment by wangxin688** [comment]
> I've successfully implemented synchronous GET operations with minimal adjustments to the Rust core. However, we're currently facing challenges with getnext/getbulk, and I'm actively investigating and addressing these issues.

omg, you guys are absolutely amazing. I was just trying to start with source code, I see the docs has been updated, thanks

**Comment by dvolodin7** [comment]
Building of binary wheels for MacOS and for MUSL is disabled for now.
You may try to install rust toolchain using tools/build/setup-rust.sh script.
